Do_An/CFSM/ViewModels/CustomerViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Domain.Entities.Helpers;
using Application.DTOs;

namespace CFSM.ViewModels
{
    public class CustomerViewModel
    {
        public PaginatedList<CustomerDto> Customers { get; set; }
        public SelectList Types { get; set; }
        public string CustomerType { get; set; }
        public string SearchString { get; set; }
        public string SortOrder { get; set; }

    }
}

Do_An/CFSM/ViewModels/IngredientViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Domain.Entities.Helpers;
using Application.DTOs;

namespace CFSM.ViewModels
{
    public class IngredientViewModel
    {
        public PaginatedList<IngredientDto> Ingredients { get; set; }
        public SelectList Types { get; set; }
        public string IngredientType { get; set; }
        public string SearchString { get; set; }
        public string SortOrder { get; set; }

    }
}

Do_An/CFSM/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Domain.Entities.Helpers;
using Domain.Repositories;
using CFSM.ViewModels;
using Application.Interfaces;
using Application.DTOs;

namespace CFSM.Controllers
{
    public class CustomerController : Controller
    {
        private readonly ICustomerService customerService;

        public CustomerController(ICustomerService customerService)
        {
            this.customerService = customerService;
        }

        public IActionResult Index(string sortOrder, string customerType, string searchString, int pageIndex = 1)
        {
            int pageSize = 10;
            int count;
            var customers = customerService.GetCustomers(sortOrder, customerType, searchString, pageIndex, pageSize, out count );
            var types = customerService.GetTypes();

            var indexVM = new CustomerViewModel()
            {
                Customers = new PaginatedList<CustomerDto>(customers, count, pageIndex, pageSize),
                Types = new SelectList(types),
                CustomerType = customerType,
                SearchString = searchString,
                SortOrder = sortOrder
            };

            return View(indexVM);
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(CustomerDto customer)
        {
            if (ModelState.IsValid)
            {
                customerService.CreateCustomer(customer);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int id)
        {
            var customer = customerService.GetCustomer(id);

            return View(customer);
        }

        [HttpPost]
        public IActionResult Edit(CustomerDto customer)
        {
            if (ModelState.IsValid)
            {
                customerService.UpdateCustomer(customer);

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            var customer = customerService.GetCustomer(id);

            return View(customer);
        }

        public IActionResult Delete(int id)
        {
            var customer = customerService.GetCustomer(id);

            return View(customer);
        }

        [HttpPost]
        public IActionResult Delete(int id, bool notUsed)
        {
            customerService.DeleteCustomer(id);

            return RedirectToAction("Index");
        }
    }
}

Do_An/CFSM/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CFSM.ViewModels;

namespace CFSM.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Do_An/CFSM/Controllers/IngredientController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Domain.Entities.Helpers;
using Domain.Repositories;
using CFSM.ViewModels;
using Application.Interfaces;
using Application.DTOs;

namespace CFSM.Controllers
{
    public class IngredientController : Controller
    {
        private readonly IIngredientService ingredientService;

        public IngredientController(IIngredientService ingredientService)
        {
            this.ingredientService = ingredientService;
        }

        public IActionResult Index(string sortOrder, string ingredientType, string searchString, int pageIndex = 1)
        {
            int pageSize = 10;
            int count;
            var ingredients = ingredientService.GetIngredients(sortOrder, ingredientType, searchString, pageIndex, pageSize, out count );
            var types = ingredientService.GetTypes();

            var indexVM = new IngredientViewModel()
            {
                Ingredients = new PaginatedList<IngredientDto>(ingredients, count, pageIndex, pageSize),
                Types = new SelectList(types),
                IngredientType = ingredientType,
                SearchString = searchString,
                SortOrder = sortOrder
            };

            return View(indexVM);
        }
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        public IActionResult Create(IngredientDto ingredient)
        {
            if (ModelState.IsValid)
            {
                ingredientService.CreateIngredient(ingredient);
                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Edit(int id)
        {
            var ingredient = ingredientService.GetIngredient(id);

            return View(ingredient);
        }

        [HttpPost]
        public IActionResult Edit(IngredientDto ingredient)
        {
            if (ModelState.IsValid)
            {
                ingredientService.UpdateIngredient(ingredient);

                return RedirectToAction("Index");
            }

            return View();
        }

        public IActionResult Details(int id)
        {
            var ingredient = ingredientService.GetIngredient(id);

            return View(ingredient);
        }

        public IActionResult Delete(int id)
        {
            var ingredient = ingredientService.GetIngredient(id);

            return View(ingredient);
        }

        [HttpPost]
        public IActionResult Delete(int id, bool notUsed)
        {
            ingredientService.DeleteIngredient(id);

            return RedirectToAction("Index");
        }
    }
}

Do_An/CFSM/Views/Customer/Create.cshtml
@model CustomerDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Customer</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerName" class="control-label"></label>
                <input asp-for="CustomerName" class="form-control"/>
                <span asp-validation-for="CustomerName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control"/>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control"/>
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Point" class="control-label"></label>
                <input asp-for="Point" class="form-control" value="0" readonly="readonly"/>
                <span asp-validation-for="Point" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <label asp-for="CustomerType" class="control-label"></label>
                <input asp-for="CustomerType" class="form-control" value="0" readonly="readonly"/>
                <span asp-validation-for="CustomerType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Do_An/CFSM/Views/Customer/Index.cshtml
@model CustomerViewModel

@{
    ViewData["Title"] = "Customer List";
    var customerNameSort = (Model.SortOrder == "customerName") ? "customerName_desc" : "customerName";
    var phoneNumberSort = (Model.SortOrder == "phoneNumber") ? "phoneNumber_desc" : "phoneNumber";
    var addressSort = (Model.SortOrder == "address_desc") ? "address" : "address_desc";
    var emailSort = (Model.SortOrder == "email_desc") ? "email" : "email_desc";
    var pointSort = (Model.SortOrder == "point_desc") ? "point" : "point_desc";
    var customerTypeSort = (Model.SortOrder == "customerType_desc") ? "customerType" : "customerType_desc";

}

<h1>Customer Manager</h1>

<form method="GET">
    <p>
        <select asp-for="CustomerType" asp-items="Model.Types">
            <option value="">All</option>
        </select>
        <input customerType="text" asp-for="SearchString"/>
        <input customerType="submit" value="Filter"/>
    </p>
</form>

<p>
    <a asp-action="Create">Create new</a>
</p>

<table class="table">
    <thead>
        <tr>
             <th>
                @Html.DisplayNameFor(model => model.Customers[0].CustomerID)</th>
            <th><a  asp-route-sortOrder="@customerNameSort"
                    asp-route-customerType="@Model.CustomerType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Customers[0].CustomerName)</a></th>
            <th><a  asp-route-sortOrder="@phoneNumberSort"
                    asp-route-customerType="@Model.CustomerType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Customers[0].PhoneNumber)</a></th>            
            <th><a  asp-route-sortOrder="@addressSort"
                    asp-route-customerType="@Model.CustomerType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Customers[0].Address)</a></th>
            <th><a  asp-route-sortOrder="@emailSort"
                    asp-route-customerType="@Model.CustomerType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Customers[0].Email)</a></th>
                 <th><a  asp-route-sortOrder="@pointSort"
                    asp-route-customerType="@Model.CustomerType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Customers[0].Point)</a></th>
            <th><a  asp-route-sortOrder="@customerTypeSort"
                    asp-route-customerType="@Model.CustomerType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Customers[0].CustomerType)</a></th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var customer in Model.Customers)
    {
        <tr>
            <td>@customer.CustomerID</td>
            <td>@customer.CustomerName</td>
            <td>@customer.PhoneNumber</td>
            <td>@customer.Address</td>
            <td>@customer.Email</td> 
            <td>@customer.Point</td>       
            <td>@customer.CustomerType</td>
            <td>
                <a asp-action="Edit" asp-route-id="@customer.CustomerID">Edit</a> |
                <a asp-action="Details" asp-route-id="@customer.CustomerID">Details</a> |
                <a asp-action="Delete" asp-route-id="@customer.CustomerID">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

@{
    var prevDisabled = !Model.Customers.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Customers.HasNextPage ? "disabled" : "";
}

<a  class="btn btn-default @prevDisabled"
    asp-route-customerType="@Model.CustomerType"
    asp-route-searchString="@Model.SearchString"
    asp-route-pageIndex="@(Model.Customers.PageIndex -1)">Previous</a>
<a  class="btn btn-default @nextDisabled"
    asp-route-customerType="@Model.CustomerType"
    asp-route-searchString="@Model.SearchString"
    asp-route-pageIndex="@(Model.Customers.PageIndex +1)">Next</a>

Do_An/CFSM/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
}

<img src="https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?ixlib=rb-1.2.1&auto=format&fit=crop&w=1057&q=80" alt="Home">

Do_An/CFSM/Views/Ingredient/Create.cshtml
@model IngredientDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<h4>Ingredient</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <input asp-for="Supplier" class="form-control"/>
                <span asp-validation-for="Supplier" class="text-danger"></span>
            </div>           
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>(VND)
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
             <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control"/>
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" value="0" readonly="readonly"/>
                <span asp-validation-for="Quantity" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Do_An/CFSM/Views/Ingredient/Delete.cshtml
@model IngredientDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Ingredient</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Name)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Name)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Supplier)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Supplier)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Price)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Price)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Quantity)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Quantity)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Unit)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Unit)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Type)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Type)</dd>
    </dl>

    <form method="POST">
        <input type="hidden" asp-route-id="@Model.Id"/>
        <input type="submit" value="Delete" class="btn btn-danger"/>
        <a asp-action="Index">Back to list</a>
    </form>
</div>

Do_An/CFSM/Views/Ingredient/Details.cshtml
@model IngredientDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Ingredient</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Name)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Name)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Supplier)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Supplier)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Price)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Price) VND</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Quantity)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Quantity)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Unit)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Unit)</dd>
        <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Type)</dt>
        <dd class="col-sm-10">@Html.DisplayFor(model => Model.Type)</dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to list</a>
</div>

Do_An/CFSM/Views/Ingredient/Edit.cshtml
@model IngredientDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>
<h4>Ingredient</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form method="POST">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control"/>
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <input asp-for="Supplier" class="form-control"/>
                <span asp-validation-for="Supplier" class="text-danger"></span>
            </div>            
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label> (VND)
                <input asp-for="Price" class="form-control"/>
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Unit" class="control-label"></label>
                <input asp-for="Unit" class="form-control" />
                <span asp-validation-for="Unit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label></br>
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new {@readonly = "readonly", @class="form-control"} })
            </div>
            <div class="form-group">
                <label asp-for="Type" class="control-label"></label>
                <input asp-for="Type" class="form-control"/>
                <span asp-validation-for="Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Do_An/CFSM/Views/Ingredient/Index.cshtml
@model IngredientViewModel

@{
    ViewData["Title"] = "Ingredient List";
    var nameSort = (Model.SortOrder == "name") ? "name_desc" : "name";
    var supplierSort = (Model.SortOrder == "supplier") ? "supplier_desc" : "supplier";
    var unitSort = (Model.SortOrder == "unit_desc") ? "unit" : "unit_desc";
    var quantitySort = (Model.SortOrder == "quantity_desc") ? "quantity" : "quantity_desc";
    var typeSort = (Model.SortOrder == "type_desc") ? "type" : "type_desc";

}

<h1>Ingredient Manager</h1>

<form method="GET">
    <p>
        <select asp-for="IngredientType" asp-items="Model.Types">
            <option value="">All</option>
        </select>
        <input type="text" asp-for="SearchString"/>
        <input type="submit" value="Filter"/>
    </p>
</form>

<p>
    <a asp-action="Create">Create new</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th><a  asp-route-sortOrder="@nameSort"
                    asp-route-ingredientType="@Model.IngredientType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Ingredients[0].Name)</a></th>
            <th><a  asp-route-sortOrder="@supplierSort"
                    asp-route-ingredientType="@Model.IngredientType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Ingredients[0].Supplier)</a></th>
            <th >
                @Html.DisplayNameFor(model => model.Ingredients[0].Price) (VND)</th>
            <th><a  asp-route-sortOrder="@unitSort"
                    asp-route-ingredientType="@Model.IngredientType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Ingredients[0].Unit)</a></th>
            <th><a  asp-route-sortOrder="@quantitySort"
                    asp-route-ingredientType="@Model.IngredientType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Ingredients[0].Quantity)</a></th>
            <th><a  asp-route-sortOrder="@typeSort"
                    asp-route-ingredientType="@Model.IngredientType"
                    asp-route-searchString="@Model.SearchString">
                @Html.DisplayNameFor(model => model.Ingredients[0].Type)</a></th>
            <th>Action</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var ingredient in Model.Ingredients)
    {
        <tr>
            <td>@ingredient.Name</td>
            <td>@ingredient.Supplier</td>
            <td>@Html.DisplayFor(item => ingredient.Price)</td> 
            <td>@ingredient.Unit</td>
            <td>@ingredient.Quantity</td>            
            <td>@ingredient.Type</td>
            <td>
                <a asp-action="Edit" asp-route-id="@ingredient.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@ingredient.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@ingredient.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

@{
    var prevDisabled = !Model.Ingredients.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.Ingredients.HasNextPage ? "disabled" : "";
}

<a  class="btn btn-default @prevDisabled"
    asp-route-ingredientType="@Model.IngredientType"
    asp-route-searchString="@Model.SearchString"
    asp-route-pageIndex="@(Model.Ingredients.PageIndex -1)">Previous</a>
<a  class="btn btn-default @nextDisabled"
    asp-route-ingredientType="@Model.IngredientType"
    asp-route-searchString="@Model.SearchString"
    asp-route-pageIndex="@(Model.Ingredients.PageIndex +1)">Next</a>

Do_An/CFSM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white box-shadow border-bottom mb-3">
            <div class="container">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-action="Index" asp-controller="Home">Home</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-action="Index" asp-controller="Ingredient">Ingredient</a>
                    </li>
                    <li>
                        <a class="nav-link text-dark" asp-action="Index" asp-controller="Customer">Customer</a>
                    </li>
                    
                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer>

    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>